### ISSUE TITLE
Error detected while processing function poshcomplete#CompleteCommand..webapi#json#decode

### ISSUE THREAD

**Issue by red8888** [cd01/poshcomplete-vim#13]
Running version 0.1.32
Win 7 x86
PSVersion 4.0

Using pathogen

Here is the version of curl I have installed: 
curl 7.31.0 (i386-pc-win32) libcurl/7.31.0 OpenSSL/0.9.8y zlib/1.2.6 libssh2/1.4.3

For installing vimproc I dropped vimproc_win32.dll into bundle\vimproc.vim\autoload and ran mingw32-make -f make_mingw32.mak. It run without any errors. I read at this link I had to put the dll in the autoload folder: http://www.4thinker.com/vim-shougo.html

When I run :call poshcomplete#StartServer() in Vim A cmd prompt comes up running a command like this and then closes without displaying any errors: 
cmd.exe /c (curl -s -k -i ^"http://localhost:1234/poshcomplete/test^" ^>C:\Users\Me\AppData\Local\Temp\VIo6382.tmp 2^>^&1")

When I try to do completion I get this error:
Error detected while processing function poshcomplete#CompleteCommand..webapi#json#decode:
line 33:
E15: Invalid expression

Let me know if you need more info.

**Comment by cd01** [comment]
> Error detected while processing function poshcomplete#CompleteCommand..webapi#json#decode:
line 33:

I guessed from this error that [webapi-vim](https://github.com/mattn/webapi-vim) doesn't installed.
Please check that [webapi-vim](https://github.com/mattn/webapi-vim) installed.

In addition, check to whether to open http://localhost:1234/poshcomplete/test in browser.

**Comment by red8888** [comment]
Thanks for replying. I installed webapi-vim, but apparently incorrectly because I can't open that link. I'll make sure I get that working then. Thanks again.

**Comment by red8888** [comment]
I'll close this and open another issue is this problem continues after I get webapi working.
