### ISSUE TITLE
how do I use vimproc?

### ISSUE THREAD

**Issue by chantisnake** [cd01/poshcomplete-vim#14]
I downloaded the .dll file, I have read the readme of vimproc, which is all about how to build it....

so, what should I do with this .dll file?

**Comment by cd01** [comment]
Put `vimproc_win(32|64).dll` under `%USERPROFILE%\vimfiles\autoload` instead of building vimproc.

> Manual Install
> 
> * Clone this repo
> * Build vimproc's native extensions (see Building for details)
> * Copy autoload/*, lib/* and plugin/* files to your 'runtimepath' directory (see :help runtimepath).
>
> https://github.com/Shougo/vimproc.vim#manual-install

If you want to build vimproc yourself, Please read [here](https://github.com/Shougo/vimproc.vim#windows).
